version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: healthcheckr_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # Use variables from the .env file
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  checker:
    build:
      context: ./checker
      dockerfile: ../Dockerfile.python
    container_name: healthcheckr_checker
    command: python checker.py
    # Use variables from the .env file
    environment:
      - DB_HOST=db
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - PYTHONUNBUFFERED=1
    depends_on:
      - db

  webapp:
    build:
      context: ./webapp
      dockerfile: ../Dockerfile.python
    container_name: healthcheckr_webapp
    ports:
      - "5000:5000"
    # Use variables from the .env file
    environment:
      - DB_HOST=db
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db

volumes:
  postgres_data: