services:
  # A PostgreSQL database on Render's free plan
  - type: pserv
    name: healthcheckr-db
    plan: free
    postgres:
      version: "14"

  # The Flask web app, using your image from Docker Hub
  - type: web
    name: healthcheckr-webapp
    plan: free
    env: docker
    image:
      url: docker.io/silentlover/healthcheckr-webapp:latest # <-- Change username if needed
    envVars:
      # Render automatically links this to the database service above
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: healthcheckr-db
          property: connectionString

  # The Python background checker, also using an image from Docker Hub
  - type: worker
    name: healthcheckr-checker
    plan: free
    env: docker
    image:
      url: docker.io/silentlover/healthcheckr-checker:latest # <-- Change username if needed
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: healthcheckr-db
          property: connectionString
      # Add your SMTP credentials for email alerts
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SENDER_EMAIL
        value: sadhu2005@gmail.com # <-- Add your real email
      - key: SMTP_PASSWORD
        value: ryvspqlkkxqcxxuk # <-- Add your real App Password