databases:
  - name: healthcheckr-db
    plan: free

services:
  - type: web
    name: healthcheckr-webapp
    plan: free
    env: docker
    image:
      url: docker.io/silentlover/healthcheckr-webapp:latest

  - type: worker
    name: healthcheckr-checker
    plan: free
    env: docker
    image:
      url: docker.io/silentlover/healthcheckr-checker:latest
    envVars:
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SENDER_EMAIL
        value: your-email@gmail.com
      - key: SMTP_PASSWORD
        value: your-new-app-password